#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting pytube"
    cd /home/codl/dev/pytube
    if [[ $(pgrep memcached | wc -l) -ge 1 ]]; then
      su codl -c "memcached -d"
    fi
    su codl -c "python2 pytube.py &"
    stat_done
  ;;
  stop)
    stat_busy "Stopping pytube"
    for i in $(ps -Ao pid,args | grep "python2 pytube.py"\
      | grep -v grep | cut -d" " -f2); do kill $i; done
    stat_done
  ;;
  restart)
    $0 stop
    $0 start
  ;;
  *)
    echo "usage: $0 {start|stop|restart}"
	;;
esac
exit 0

# vim: tw=70 ts=2 sw=2
